OPENAI = 'openai'
FIREWORKS = 'fireworks'

LLM_TYPE = 'LLM_TYPE'
EMBED_MODEL_TYPE = 'EMBED_MODEL_TYPE'

OPENAI_MODEL = 'OPENAI_MODEL'
FIREWORKS_LLM = 'FIREWORKS_LLM'

OPENAI_API_KEY = 'OPENAI_API_KEY'
FIREWORKS_API_KEY = 'FIREWORKS_API_KEY'
EMBED_BATCH_SIZE = 'EMBED_BATCH_SIZE'